development:
  adapter: sqlite3
  database: tmp/pivotpong_development.db

test: &test
  adapter: sqlite3
  database: tmp/pivotpong_test.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: pivotpong
  password:
  min_messages: warning
  database: pivotpong_production
